framework: mocha
tier: xlarge
postMerge: 
  pattern: 
    - "./test/*-test.js"
preMerge:
  pattern:
    - "./test/*-test.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.0
