framework: mocha
tier: xlarge
postMerge:
  pattern: 
    - "./test/d3-test.js"
preMerge:
  pattern:
    - "./test/d3-test.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.0